### ISSUE TITLE
恕我直言，建议替换掉Spring Security

### ISSUE THREAD

**Issue by cm215** [valarchie/AgileBoot-Back-End#12]
当然这只是我的个人意见，建议换成Sa-Token，认证授权的代码会变得更加简洁清晰。

**Comment by valarchie** [comment]
已放到TODO List   感谢您的建议   
欢迎PR

**Comment by valarchie** [comment]
查了一下这个Sa-token  刚出来不久
选择一个框架  不仅考虑是否简单易用   还需要看看这个框架使用的人多不多  
目前Spring Security 和 Shiro应该是使用最多的框架

**Comment by xiaomizhou2** [comment]
Spring Secuity是有相当的使用门槛 但是扩展性是很强大的 配合Oauth2做统一身份认证是很好的，但是中小型项目的话 建议使用shiro

**Comment by valarchie** [comment]
> Spring Secuity是有相当的使用门槛 但是扩展性是很强大的 配合Oauth2做统一身份认证是很好的，但是中小型项目的话 建议使用shiro

嗯 感谢你的意见   是的。   但是现在项目是Spring Security  好像就比较没必要改回Shiro

**Comment by valarchie** [comment]
原版ruoyi的  Security 相关度 登录代码   的确挺费解。  今天会重构一下。

**Comment by valarchie** [comment]
重构完毕。
