### ISSUE TITLE
请问优化异步服务这个优化点做了哪些的修改与原框架的相比有些什么优缺点？

### ISSUE THREAD

**Issue by dreamparis** [valarchie/AgileBoot-Back-End#17]

**Comment by valarchie** [comment]
优化的只是代码上的写法。
![图片](https://user-images.githubusercontent.com/18179028/211246342-abd79c84-6226-4d97-9ea2-c5b880aa29cb.png)
原版的多线程工具类是通过注入的形式 填充到AsyncManager.  
我认为没有必要。  原版的AsyncManager调用前，一定要调用me()方法，我也认为没有必要。

原版Async工厂类的代码优化
![图片](https://user-images.githubusercontent.com/18179028/211246732-822d2963-fef9-41a3-80ee-0411c878732b.png)
