### ISSUE TITLE
服务监控报错：could not initialize class oshi.driver.windows.perfmon.PerfmonDisabled

### ISSUE THREAD

**Issue by CuYheng** [valarchie/AgileBoot-Back-End#18]
**BUG描述**

这个<oshi.version>6.1.6</oshi.version>依赖组件有点老了，在我这个window10_22h2_19045.2364版本下，有个类型错误(不同)的注册表键值，导致无法初始化这个类，

**正确的行为**
升级最新版本即可解决 <oshi.version>6.4.0</oshi.version>

**桌面端:**
 - 操作系统: Windows 10 专业版 22H2 19045.2364

**Comment by valarchie** [comment]
感谢您的指正。 晚些时候我会fix。

**Comment by valarchie** [comment]
fixed. 已升级至6.4.0
