### ISSUE TITLE
能加入不，挺感兴趣的

### ISSUE THREAD

**Issue by kinsey-jian** [valarchie/AgileBoot-Back-End#22]
**您的功能请求是否与问题相关？ 请描述。**
清楚简明地描述问题所在。 

**描述您想要的解决方案**
对您所设想的问题的清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑过的任何替代解决方案或功能的清晰简洁的描述。

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by valarchie** [comment]
可以呀~  非常欢迎大佬加入。
本项目的初衷就是做一个规范的全栈项目。适合生产以及供初学者参考学习的项目。
群号：1398880.    欢迎进来讨论~

**Comment by valarchie** [comment]
核心commiter  到时候可以申请IDEA license.
