### ISSUE TITLE
我可以参与项目的开发吗，哈哈哈

### ISSUE THREAD

**Issue by jinronga** [valarchie/AgileBoot-Back-End#24]
**您的功能请求是否与问题相关？ 请描述。**
清楚简明地描述问题所在。 

**描述您想要的解决方案**
对您所设想的问题的清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑过的任何替代解决方案或功能的清晰简洁的描述。

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by valarchie** [comment]
可以呀。 非常欢迎小伙伴加入。
可以先加群一起讨论。 1398880.
