### ISSUE TITLE
似乎无 mysql 与 redis 无法启动

### ISSUE THREAD

**Issue by Shimada666** [valarchie/AgileBoot-Back-End#27]
<img width="1954" alt="image" src="https://user-images.githubusercontent.com/33391300/221399809-23475286-a8ca-4cf8-8c71-928fdab47567.png">

**Comment by valarchie** [comment]
我测试了一下  是可以启动的。  你有做其他改动吗？ 
![图片](https://user-images.githubusercontent.com/18179028/221400240-c233c92e-7e2a-40cd-9453-ddbfb989fc48.png)
这边的启动yml是basic和test吗？

**Comment by Shimada666** [comment]
> 我测试了一下 是可以启动的。 你有做其他改动吗？ ![图片](https://user-images.githubusercontent.com/18179028/221400240-c233c92e-7e2a-40cd-9453-ddbfb989fc48.png) 这边的启动yml是basic和test吗？

是的，jdk8，从master刚拷贝的代码，仅作图中改动

**Comment by valarchie** [comment]
能不能帮忙check一个问题
因为redis的端口是36379
怀疑是端口被占用了   你看看换个端口号能不能启动
![图片](https://user-images.githubusercontent.com/18179028/221401431-030d1f57-8b60-4633-b77a-2333b88c253a.png)

**Comment by valarchie** [comment]
怎么样 小哥  可以run起来吗

**Comment by valarchie** [comment]
端口问题  或者是 MacOS兼容问题
