### ISSUE TITLE
无redis,mysql运行bug

### ISSUE THREAD

**Issue by BelldandyzZ** [valarchie/AgileBoot-Back-End#33]
下载项目,跑了前端,没配数据库和redis,按照文档修改dev为test,以及另外两个修改为true,启动失败,自己修改了一下其他配置,启动成功但是登陆不成功

**Comment by valarchie** [comment]
你好。 你的系统是什么系统？
Java后台 有报什么错吗？
浏览器请求接口报什么错？

**Comment by valarchie** [comment]
mac os 新系统启动redis会有问题， 已在readMe中 加上说明。 sorry
