### ISSUE TITLE
SysDeptServiceImpl 中会报 Could not autowire. No beans of 'SysUserMapper' type found. 错误

### ISSUE THREAD

**Issue by liugt34** [valarchie/AgileBoot-Back-End#34]
SysDeptServiceImpl类中会报这个错

```
    @NonNull
    private SysUserMapper userMapper;
```

Could not autowire. No beans of 'SysUserMapper' type found.

**Comment by liugt34** [comment]
![image](https://github.com/valarchie/AgileBoot-Back-End/assets/8056013/e34797b4-105b-46fc-92f2-4e8b376b21c5)

**Comment by valarchie** [comment]
你有实际启动起来过吗？  这个类是能装载的。
我这边是不会报错的..   是不是你的IDEA版本比较低一点  没有识别到
![image](https://github.com/valarchie/AgileBoot-Back-End/assets/18179028/0c838c71-a50b-4709-b590-9ff2792eea29)

**Comment by liugt34** [comment]
我加了一个 @Resource 就可以了
