### ISSUE TITLE
有没有像若依那样的代码生成的模块

### ISSUE THREAD

**Issue by shusqn** [valarchie/AgileBoot-Back-End#37]
**您的功能请求是否与问题相关？ 请描述。**
清楚简明地描述问题所在。 

**描述您想要的解决方案**
对您所设想的问题的清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑过的任何替代解决方案或功能的清晰简洁的描述。

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by valarchie** [comment]
在这个类中CodeGenerator   可以生成 Controller Service DAO   你可以看看这个类。
具体生成代码的模块  因为本项目不是简单的一个entity加MVC三层透传的模式，所以完全自动代码生成比较困难。所以这一块就没有做。
