### ISSUE TITLE
可否将用户角色设为可多选

### ISSUE THREAD

**Issue by turancnx** [valarchie/AgileBoot-Back-End#44]
使用了一段时间AgileBoot写了几个项目，感觉非常不错。不过碰到个小问题，现在用户角色仅能单选，有点不太灵活，业务中有时需要多选角色，现在只能通过创建新的角色来组合角色权限，但组合情况多了的话就会变得很复杂。

**Comment by valarchie** [comment]
你好， 非常抱歉。  之前设想的是单角色可以满足大多数用户的需求， 所以就改成单角色了。  
多角色的话  可能需要您自己做一下调整。

**Comment by turancnx** [comment]
OK，感谢
