### ISSUE TITLE
亲，拉取代码下来，本地没运营起来，能否有个联系方式，在线指导一下啊？

### ISSUE THREAD

**Issue by hujingyang2008** [valarchie/AgileBoot-Back-End#49]
![企业微信截图_16950287306086](https://github.com/valarchie/AgileBoot-Back-End/assets/74450479/0a360fe4-7407-4411-884b-1b483f2a6943)

**Comment by valarchie** [comment]
readme 有技术群

**Comment by hujingyang2008** [comment]
好的，申请了，麻烦通过一下
