### ISSUE TITLE
前端在打开超过二个页面时，其他页面会出现空白页，无论点击那个页面后都是空白的

### ISSUE THREAD

**Issue by yuaotianAI** [valarchie/AgileBoot-Back-End#62]
![image](https://github.com/valarchie/AgileBoot-Back-End/assets/114507148/150cbd12-2592-4043-888a-9554d5ce8096)

但是在我打开二个个页面以上后会其他页面会立马变成空白页，无论点击那个页面后都是空白的，即使原来那个页面也是一样，也没有任何网络请求，直到我F5刷新整个页面才不会。

前后端版本：前天刚刚下载的，最新的代码，
chrome 版本 119.0.6045.160（正式版本） （64 位）

**Comment by valarchie** [comment]
有做什么其他改动吗？  console 可以帮忙看下 有没有什么报错。
我这边没有出现这个情况。

**Comment by yuaotianAI** [comment]
而且我发现好像只有我自己添加的三个路由，工程项目、日常项目、配置，只要我随便打开一个页面，然后打开其他的页面就会空白，除非我刷新，

下面是我写的页面代码，最简单的一个页面了。

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { getPmSystemConfig, savePmSystemConfig } from "@/api/pm/config";
import { ElButton, ElForm, ElFormItem, ElInput, ElMessage } from "element-plus";

defineOptions({
  name: "PmConfig"
});

const ipShareAddress = ref("");
const shareFolder = ref("");
const localFolder = ref("");

// 页面加载时调用
onMounted(() => {
  // 获取配置信息
  getPmSystemConfig().then(res => {
    ipShareAddress.value = res.data.ipShareAddress;
    shareFolder.value = res.data.shareFolder;
    localFolder.value = res.data.localFolder;
  });
});

const saveConfig = async () => {
  savePmSystemConfig({
    ipShareAddress: ipShareAddress.value,
    shareFolder: shareFolder.value,
    localFolder: localFolder.value
  })
    .then(() => {
      ElMessage.success("保存成功");
    })
    .catch(() => {
      ElMessage.error("保存失败");
    });
};
</script>

<template>
  <div class="config-container">
    <ElForm label-position="right" label-width="100px" class="form-container">
      <h1>配置管理</h1>
      <ElFormItem label="IP共享地址：">
        <ElInput v-model="ipShareAddress" placeholder="请输入IP共享地址" />
      </ElFormItem>
      <ElFormItem label="本地目录：">
        <ElInput v-model="localFolder" placeholder="请输入本地文件夹路径" />
      </ElFormItem>
      <ElFormItem label="共享文件夹：">
        <ElInput v-model="shareFolder" placeholder="请输入共享文件夹路径" />
      </ElFormItem>
      <ElFormItem>
        <ElButton type="primary" @click="saveConfig">保存</ElButton>
      </ElFormItem>
    </ElForm>
  </div>
</template>

<style scoped lang="scss">
.config-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background: #f5f5f5;

  .form-container {
    padding: 20px;
    box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    background: #fff;
  }

  h1 {
    text-align: center;
    margin-bottom: 20px;
  }
}
</style>

**Comment by yuaotianAI** [comment]
是自己造成的~已经解决了，加一个div包裹即可
