### ISSUE TITLE
com.agileboot.domain.system.monitor.dto.ServerInfo#convertFileSize

### ISSUE THREAD

**Issue by kingding001** [valarchie/AgileBoot-Back-End#8]
com.agileboot.domain.system.monitor.dto.ServerInfo#convertFileSize
MB，KB数据存在小问题：

String.format(ratio > 100f ? "%.0f MB" : "%.1f MB", Constants.MB);
String.format(ratio > 100f ? "%.1f KB" : "%.1f KB", Constants.KB);
to:
String.format(ratio > 100f ? "%.0f MB" : "%.1f MB", ratio);
String.format(ratio > 100f ? "%.1f KB" : "%.1f KB",ratio);

**Comment by valarchie** [comment]
好， 收到  我check一下

**Comment by valarchie** [comment]
```
        ServerInfo serverInfo = new ServerInfo();
        Assertions.assertEquals("0.5 KB", serverInfo.convertFileSize(512L));
        Assertions.assertEquals("1.5 KB", serverInfo.convertFileSize(1536L));
        Assertions.assertEquals("1.5 MB", serverInfo.convertFileSize(1572864));
        Assertions.assertEquals("1.5 GB", serverInfo.convertFileSize(1610612736L));
```

修改了代码，新增了UT覆盖。 感谢老哥指正。

**Comment by valarchie** [comment]
非常感谢。 欢迎指正项目中的不足。  一起探讨项目的规范和写法
