### ISSUE TITLE
建议在gitee上维护一个副本,github有时候链接不上

### ISSUE THREAD

**Issue by lystrosaurus** [valarchie/AgileBoot-Back-End#9]
如题，方便的可以做一个，我们直接fork代码上传gitee上感觉不是特别合适，如果在gitee上有副本，从那fork一份会方便一些，谢谢

**Comment by valarchie** [comment]
Hi 你好
gitee的仓库是这个，gitee会同步github这边的改动
https://gitee.com/valarchie/AgileBoot-Back-End
